version : "3"
services:
    db:
        #image: "mysql:5.7"
        build: ./db/
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            #- ./db:/docker-entrypoint-initdb.d/:ro
            - ./db/mysqldb:/var/lib/mysql
        restart: always
        container_name: db
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "3306:3306"
        
    app:
        depends_on:
            - db
        container_name: app
        links:
            - db
        build: .
        restart: always
        ports:
            - "5000:5000"
        volumes:
            - ./:/app

volumes:
    db: