pipeline{
    agent none
    stages{
        /*
        stage("Git_Secret_Checks"){
            agent {label 'parham'}
            steps{
                sh 'rm trufflehog || true'
                sh 'docker run gesellix/trufflehog --json http://192.168.122.1/Myproject > trufflehog'
            }
            post{
                always{
                    sh 'cat trufflehog'    
                }
            }
        } 
        stage("SAST"){
            agent {label 'parham'}
            steps {
                sh 'rm owasp* || true'
                sh 'wget "https://raw.githubusercontent.com/lintechso/webapp/master/owasp-dependency-check.sh" '
                sh 'chmod +x owasp-dependency-check.sh'
                sh 'bash owasp-dependency-check.sh'
                sh 'cat /home/parham/OWASP-Dependency-Check/reports/dependency-check-report.xml'                
            }
        }*/
        stage("Staging Deployment"){
            agent {label 'parham'}
            when {
                expression {env.GIT_BRANCH == 'origin/dev'}
            }
            steps {
                sh 'cd src/ && cp keys.py.sample keys.py'
                sh 'cd src/ && docker-compose up -d --build && sleep 10'          
            }
        }
        stage("Staging Deployment Test"){
            agent { label 'parham'}
            when {
                expression {env.GIT_BRANCH == 'origin/dev'}
            }
            steps {
                echo "Staging Deployment Test...."          
                sh 'sleep 10'  
                sh ' docker exec -i app python3 Unit-Test.py'
            }
            post {
                success {
                    sh 'git checkout master'
                    sh 'git merge origin/dev'
                }
                failure {
                    echo 'Failed'
                }
            }
        }
        stage("Deploy"){
            agent {label 'parham'}
            when {
                expression {env.GIT_BRANCH == 'origin/master'}
            }
            steps {
                echo 'Deploying ....'               
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}