
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "website.local"
  config.vm.network :private_network, ip: "192.168.2.8"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.insert_key = 'false'
  config.vm.provider :virtualbox do |v|
    v.memory = 2048
  end

  # Ansible provisioner.
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "deploy.yml"
    ansible.limit = "all"
  end
end
